---
# Source: consul/templates/client-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: consul-client
  namespace: consul
  labels:
    app: consul
    chart: consul-helm
    heritage: Helm
    release: consul-oc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: consul-client
subjects:
  - kind: ServiceAccount
    name: consul-client
