---
# Source: consul/templates/controller-leader-election-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: consul-controller-leader-election
  labels:
    app: consul
    chart: consul-helm
    heritage: Helm
    release: consul-oc
    component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: consul-controller-leader-election
subjects:
- kind: ServiceAccount
  name: consul-controller
