---
# Source: consul/templates/server-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: consul-server
  namespace: consul
  labels:
    app: consul
    chart: consul-helm
    heritage: Helm
    release: consul-oc
rules:
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  resourceNames:
  - consul-server
  verbs:
  - use
