---
# Source: consul/templates/controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-controller
  labels:
    app: consul
    chart: consul-helm
    heritage: Helm
    release: consul-oc
    component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
      chart: consul-helm
      heritage: Helm
      release: consul-oc
      component: controller
  template:
    metadata:
      labels:
        app: consul
        chart: consul-helm
        heritage: Helm
        release: consul-oc
        component: controller
      annotations:
        "consul.hashicorp.com/connect-inject": "false"
    spec:
      containers:
      - command:
        - "/bin/sh"
        - "-ec"
        - |
          consul-k8s controller \
            -webhook-tls-cert-dir=/tmp/controller-webhook/certs \
            -datacenter=oc-us-east-poc \
            -enable-leader-election \
            -log-level="info" \
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: CONSUL_HTTP_ADDR
          value: http://$(HOST_IP):8500
        image: hashicorp/consul-k8s:0.19.0
        name: controller
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 50Mi
        volumeMounts:
        - mountPath: /tmp/controller-webhook/certs
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: consul-controller-webhook-cert
      serviceAccountName: consul-controller
