---
# Source: consul/templates/client-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: consul-client
  namespace: consul
  labels:
    app: consul
    chart: consul-helm
    heritage: Helm
    release: consul-oc
rules:
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    resourceNames:
    - consul-client
    verbs:
    - use
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames:
      - consul-client
    verbs:
      - use
